### ISSUE TITLE
是否有变化检测的预训练模型

### ISSUE THREAD

**Issue by KrisZHH** [PaddlePaddle/PaddleRS#102]
语义分割、目标检测等任务可以在PaddleSeg和PaddleDet中找到预训练模型，但是没有找到变化检测相关预训练模型，不知后续是否会提供？

**Comment by Bobholamovic** [comment]
目前PaddleRS为12个模型提供[LEVIR-CD建筑物变化检测数据集](https://justchenhao.github.io/LEVIR/)上的预训练权重，模型完整列表在[此处](https://github.com/PaddlePaddle/PaddleRS/blob/a568952b6aa80449d02573ec6db412e53217a1a7/paddlers/utils/checkpoint.py#L430)可以查看。

PaddleRS目前不对外提供预训练模型的下载接口或链接，需要使用预训练变化检测模型初始化权重参数可在训练器`train()`方法中指定`pretrain_weights`参数为`'LEVIRCD'`。

**Comment by KrisZHH** [comment]
那请问这些变化检测模型中，哪个在levir-cd上指标是最好的呢？请问是否有实验记录呢？

**Comment by Bobholamovic** [comment]
> 那请问这些变化检测模型中，哪个在levir-cd上指标是最好的呢？请问是否有实验记录呢？

这些模型只经过『粗训练』（尚未经过精细化调参），所以只做预训练加载用，不做benchmark。目前没有记录具体精度，但已知『粗训练』模型中精度最高的是P2V-CD。

我们正在完善遥感影像变化检测模型的benchmark中。

**Comment by Bobholamovic** [comment]
遥感影像变化检测任务公开benchmark可参考这里：
https://paperswithcode.com/task/change-detection
https://paperswithcode.com/task/change-detection-for-remote-sensing-images
https://paperswithcode.com/task/building-change-detection-for-remote-sensing

PaddleRS中的ChangeFormer、FCCDN、STANet、SNUNet、P2V-CD等变化检测模型均经过严格验证，在相同超参数配置条件下能够达到或超越原论文精度，其中P2V-CD为原作者官方实现；BIT、DSIFN等在模型大小和计算量与原文相同的情况下能够取得超过原文的精度指标（尚未做同超参数条件下的测试）；部分模型如CDNet、FCSiamConc由于论文发表时间较早，文中未提供当前流行的变化检测数据集上的精度指标，故无法与原文对齐，但经过测试，PaddleRS中集成的这部分模型在SVCD数据集上也可以取得90%以上的F1-score。
