### ISSUE TITLE
ValueError: (InvalidArgument) yolo_box(): argument 'X' (position 0) must be Tensor, but got Tensor (at ..\paddle\fluid\pybind\op_function_common.cc:818)

### ISSUE THREAD

**Issue by zjqqwn** [PaddlePaddle/PaddleRS#103]
欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：PaddleRS 1.0b0
 3. PaddlePaddle版本：PaddlePaddle 2.4.2
 4. 操作系统信息：Windows
 5. Python版本号：Python3.7
 6. CUDA/cuDNN版本：无（集成显卡）
 7. 代码如下：
`from paddlers.tasks.object_detector import PPYOLOv2
num_classes = len(train_dataset.labels)#项目数
model = PPYOLOv2(num_classes=num_classes)
model.train(
    num_epochs=30, 
    train_dataset=train_dataset,
    train_batch_size=10,
    eval_dataset=eval_dataset,
    pretrain_weights="COCO",
    learning_rate=3e-5,
    warmup_steps=10,
    warmup_start_lr=0.0,
    save_interval_epochs=5,
    lr_decay_epochs=[10, 20],
    save_dir="output",
    use_vdl=True)`
 8. 报错如下：
2023-03-08 08:56:07 [INFO]	Start to evaluate(total_samples=945, total_steps=945)...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-6776ba3d5223> in <module>()
     12     lr_decay_epochs=[10, 20],
     13     save_dir="output",
---> 14     use_vdl=True)

D:\anaconda3-5.3.1\lib\site-packages\paddlers\tasks\object_detector.py in train(self, num_epochs, train_dataset, train_batch_size, eval_dataset, optimizer, save_interval_epochs, log_interval_steps, save_dir, pretrain_weights, learning_rate, warmup_steps, warmup_start_lr, lr_decay_epochs, lr_decay_gamma, metric, use_ema, early_stop, early_stop_patience, use_vdl, resume_checkpoint)
    332             early_stop=early_stop,
    333             early_stop_patience=early_stop_patience,
--> 334             use_vdl=use_vdl)
    335 
    336     def quant_aware_train(self,

D:\anaconda3-5.3.1\lib\site-packages\paddlers\tasks\base.py in train_loop(self, num_epochs, train_dataset, train_batch_size, eval_dataset, save_interval_epochs, log_interval_steps, save_dir, ema, early_stop, early_stop_patience, use_vdl)
    428                         eval_dataset,
    429                         batch_size=eval_batch_size,
--> 430                         return_details=True)
    431                     # 保存最优模型
    432                     if local_rank == 0:

D:\anaconda3-5.3.1\lib\site-packages\paddlers\tasks\object_detector.py in evaluate(self, eval_dataset, batch_size, metric, return_details)
    497             with paddle.no_grad():
    498                 for step, data in enumerate(self.eval_data_loader):
--> 499                     outputs = self.run(self.net, data, 'eval')
    500                     eval_metric.update(data, outputs)
    501                 eval_metric.accumulate()

D:\anaconda3-5.3.1\lib\site-packages\paddlers\tasks\object_detector.py in run(self, net, inputs, mode)
    103 
    104     def run(self, net, inputs, mode):
--> 105         net_out = net(inputs)
    106         if mode in ['train', 'eval']:
    107             outputs = net_out

D:\anaconda3-5.3.1\lib\site-packages\paddle\fluid\dygraph\layers.py in __call__(self, *inputs, **kwargs)
   1010         ):
   1011             self._build_once(*inputs, **kwargs)
-> 1012             return self.forward(*inputs, **kwargs)
   1013         else:
   1014             return self._dygraph_call_func(*inputs, **kwargs)

D:\anaconda3-5.3.1\lib\site-packages\paddlers\models\ppdet\modeling\architectures\meta_arch.py in forward(self, inputs)
     69             for inp in inputs_list:
     70                 self.inputs = inp
---> 71                 outs.append(self.get_pred())
     72 
     73             # multi-scale test

D:\anaconda3-5.3.1\lib\site-packages\paddlers\models\ppdet\modeling\architectures\yolo.py in get_pred(self)
    122 
    123     def get_pred(self):
--> 124         return self._forward()

D:\anaconda3-5.3.1\lib\site-packages\paddlers\models\ppdet\modeling\architectures\yolo.py in _forward(self)
    113                     bbox, bbox_num = self.post_process(
    114                         yolo_head_outs, self.yolo_head.mask_anchors,
--> 115                         self.inputs['im_shape'], self.inputs['scale_factor'])
    116                 output = {'bbox': bbox, 'bbox_num': bbox_num}
    117 

D:\anaconda3-5.3.1\lib\site-packages\paddle\fluid\dygraph\layers.py in __call__(self, *inputs, **kwargs)
   1010         ):
   1011             self._build_once(*inputs, **kwargs)
-> 1012             return self.forward(*inputs, **kwargs)
   1013         else:
   1014             return self._dygraph_call_func(*inputs, **kwargs)

D:\anaconda3-5.3.1\lib\site-packages\paddlers\models\ppdet\modeling\post_process.py in forward(self, head_out, rois, im_shape, scale_factor)
     61         """
     62         if self.nms is not None:
---> 63             bboxes, score = self.decode(head_out, rois, im_shape, scale_factor)
     64             bbox_pred, bbox_num, _ = self.nms(bboxes, score, self.num_classes)
     65         else:

D:\anaconda3-5.3.1\lib\site-packages\paddlers\models\ppdet\modeling\layers.py in __call__(self, yolo_head_out, anchors, im_shape, scale_factor, var_weight)
    543                                          self.num_classes, self.conf_thresh,
    544                                          self.downsample_ratio // 2**i,
--> 545                                          self.clip_bbox, self.scale_x_y)
    546             boxes_list.append(boxes)
    547             scores_list.append(paddle.transpose(scores, perm=[0, 2, 1]))

D:\anaconda3-5.3.1\lib\site-packages\paddlers\models\ppdet\modeling\ops.py in yolo_box(x, origin_shape, anchors, class_num, conf_thresh, downsample_ratio, clip_bbox, scale_x_y, name)
    698                  conf_thresh, 'downsample_ratio', downsample_ratio,
    699                  'clip_bbox', clip_bbox, 'scale_x_y', scale_x_y)
--> 700         boxes, scores = core.ops.yolo_box(x, origin_shape, *attrs)
    701         return boxes, scores
    702     else:

ValueError: (InvalidArgument) yolo_box(): argument 'X' (position 0) must be Tensor, but got Tensor (at ..\paddle\fluid\pybind\op_function_common.cc:818)
请问如何解决？

**Comment by Bobholamovic** [comment]
PaddleRS v1.0b0是一个beta版本。请升级到稳定版本（PaddleRS v1.0）后查看此问题是否依然存在。
