### ISSUE TITLE
win10 安装padders 问题

### ISSUE THREAD

**Issue by YSYS101010000** [PaddlePaddle/PaddleRS#108]
欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：PaddleRS develop）
 2. PaddlePaddle版本：addlePaddle 2.3.2-gpu
 3. 操作系统信息：Windows
 4. Python版本号：Python3.8
 5. CUDA/cuDNN版本：CUDA11.1/cuDNN 8.0.4
 >>python tutorials/train/change_detection/bit.py

  File "C:\Users\Administrator\anaconda3\envs\PaddleRs\lib\site-packages\paddlers-0.0.0.dev0-py3.8.egg\paddlers\models\ppcls\arch\__init__.py", line 30, in <modu
le>
    from .distill.afd_attention import LinearTransformStudent, LinearTransformTeacher
ModuleNotFoundError: No module named 'paddlers.models.ppcls.arch.distill'

**Comment by WesternTrail** [comment]
我也有这样的问题。在运行`python tutorials/train/semantic_segmentation/deeplabv3p.py
`的时候

**Comment by WesternTrail** [comment]
> * PaddleRS版本：PaddleRS develop）
> * PaddlePaddle版本：addlePaddle 2.4
> * 操作系统信息：Windows11
> * Python版本号：Python3.8
> * CUDA/cuDNN版本：CUDA11.5/cuDNN for cuda 11.xxx

**Comment by Bobholamovic** [comment]
你好，这是一个已知bug，存在于当前develop分支。我们正在 https://github.com/PaddlePaddle/PaddleRS/pull/104 修复中。

**Comment by YSYS101010000** [comment]
> > * 划桨者版本:划桨者发展)
> > * PaddlePaddle版本:addlePaddle 2.4
> > * 操作系统信息:窗口11
> > * 计算机编程语言版本号:Python3.8
> > * CUDA/cuDNN版本:CUDA11.5/cuDNN for cuda 11.xxx

代码下载release版本

**Comment by WesternTrail** [comment]
> 你好，这是一个已知bug，存在于当前develop分支。我们正在 #104 修复中。

切换release版本管用，但是出现另外的错误：
![image](https://user-images.githubusercontent.com/28615285/224462113-bd3ff8cb-63cd-40c1-bfb2-fa4cd906341e.png)

1、我尝试过降低cuda版本到10.2，重新安装paddlepaddle。但又出现两个问题：

-        当我安装7.6.5的cudnn版本时，依然如上述报错
-        当我安装8.6.0的cudnn时，出现下述无法识别cudnn的错误

![image](https://user-images.githubusercontent.com/28615285/224462457-4ba37eea-7de5-4830-b881-0a5e5698f7de.png)

**Comment by Bobholamovic** [comment]
> > 你好，这是一个已知bug，存在于当前develop分支。我们正在 #104 修复中。
> 
> 切换release版本管用，但是出现另外的错误： ![image](https://user-images.githubusercontent.com/28615285/224462113-bd3ff8cb-63cd-40c1-bfb2-fa4cd906341e.png)
> 
> 1、我尝试过降低cuda版本到10.2，重新安装paddlepaddle。但又出现两个问题：
> 
> * ```
>      当我安装7.6.5的cudnn版本时，依然如上述报错
>   ```
> * ```
>      当我安装8.6.0的cudnn时，出现下述无法识别cudnn的错误
>   ```
> 
> ![image](https://user-images.githubusercontent.com/28615285/224462457-4ba37eea-7de5-4830-b881-0a5e5698f7de.png)

你好，这个错误看起来来自于PaddlePaddle框架而非PaddleRS工具。在安装PaddlePaddle GPU版本时，建议可以使用Anaconda工具自动下载安装合适的CUDA、cuDNN依赖包。请参考PaddlePaddle官方网站安装教程中“使用conda安装”的部分。

**Comment by YSYS101010000** [comment]
> > 你好，这是一个已知bug，存在于当前develop分支。我们正在 #104 修复中。
> 
> 切换release版本管用，但是出现另外的错误： ![image](https://user-images.githubusercontent.com/28615285/224462113-bd3ff8cb-63cd-40c1-bfb2-fa4cd906341e.png)
> 
> 1、我尝试过降低cuda版本到10.2，重新安装paddlepaddle。但又出现两个问题：
> 
> * ```
>      当我安装7.6.5的cudnn版本时，依然如上述报错
>   ```
> * ```
>      当我安装8.6.0的cudnn时，出现下述无法识别cudnn的错误
>   ```
> 
> ![image](https://user-images.githubusercontent.com/28615285/224462457-4ba37eea-7de5-4830-b881-0a5e5698f7de.png)

切
