### ISSUE TITLE
【黑客松第四期】

### ISSUE THREAD

**Issue by Harryoung** [PaddlePaddle/PaddleRS#109]
PaddleRS在[黑客松第四期](https://github.com/PaddlePaddle/Paddle/issues/51281)中发布了四道题目，分别如下。关于题目的一些疑问可以在本issue留言讨论。

### No.150：PaddleRS集成PaddleDetection的旋转框检测能力 <a name='task150'></a>

- **技术标签：Python、深度学习**
- **任务难度：进阶**⭐️⭐️
- **详细描述：**
  - PaddleRS是针对遥感影像智能解译的开发套件，已集成有语义分割、水平框目标检测等能力，现需集成PaddleDetection套件已有的旋转框目标检测能力，并提供说明文档
  - 参考：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rotate/README.md
- **提交内容：**
  - 代码、文档，合入PaddleRS套件
  - PaddleRS贡献指南 [链接](https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/CONTRIBUTING.md)
- **技术要求：**
  - 熟练掌握Python、PaddlePaddle、PaddleRS和目标检测

### No.151：PaddleRS运行环境打包，并制作端到端遥感建筑物提取教程 <a name='task151'></a>

- **技术标签：Python、docker、文档**
- **任务难度：基础**️⭐️
- **详细描述：**
  - 打包制作包含PaddleRS、EISeg、GeoView最新版本运行环境的docker镜像
  - 利用官方提供的示例遥感影像，基于前述镜像环境，跑通从数据标注（EISeg）、模型训练（PaddleRS）、部署应用（GeoView）的遥感建筑物提取全流程，并形成教程文档。
  - 遥感影像网盘地址： https://pan.baidu.com/s/1BXoQX6Z4KONbkm1gw6BXNw?pwd=ye92 提取码: ye92 
- **提交内容：**
  - docker镜像、教程文档
- **技术要求：**
  - 熟练掌握Python、docker、PaddleRS，熟悉遥感场景

### No.152：PaddleRS API 文档完善 <a name='task152'></a>

- **技术标签：文档**
- **任务难度：基础**️⭐️
- **详细描述：**
  - 撰写中英文文档，对 PaddleRS 每个模型的构造参数进行详细说明（参考 paddlers/rs_models 中的 docstring）
  - 撰写中英文文档，对 PaddleRS 每个数据预处理/数据变换算子的构造参数进行详细说明
  - 完善 PaddleRS quick start 中英文文档，在已有的『模型训练』部分内容基础上，添加『模型精度验证』与『模型部署』部分内容。
- **提交内容：**
  - 教程文档
- **技术要求：**
  - 熟悉 PaddleRS

### No.153：PaddleRS 英文文档 <a name='task153'></a>

- **技术标签：文档**
- **任务难度：基础**️⭐️
- **详细描述：**
  - 将 PaddleRS docs 目录中包含的文档内容翻译为英文，并形成相应英文文档
  - 为 PaddleRS tutorials 目录中的示例脚本添加英文注释
- **提交内容：**
  - 教程文档
- **技术要求：**
  - 熟悉 PaddleRS，外语水平良好

**Comment by enkilee** [comment]
请问，152题：模型的构造参数，有没有示例文档？比如，标题级别、小标题用I II III 还是 （1） （2） （3） 之类，有文档规范说明吗？

**Comment by Bobholamovic** [comment]
> 请问，152题：模型的构造参数，有没有示例文档？比如，标题级别、小标题用I II III 还是 （1） （2） （3） 之类，有文档规范说明吗？

目前对文档没有诸如标题级别、标题样式等统一规范，可参考PaddleRS的`docs`目录中已有文档的风格编写。此外，在提交commit前，需使用pre-commit钩子进行检查，以使其符合格式要求（主要检查空行和dead link）。

**Comment by Bobholamovic** [comment]
第四期黑客松PaddleRS全部赛题（No. 150-153）均已锁定冠军并合入PR。现关闭此issue。
