### ISSUE TITLE
黑客松第四期 152

### ISSUE THREAD

**Issue by ggggkkkknnnn** [PaddlePaddle/PaddleRS#116]
对于题目152中的
“撰写中英文文档，对 PaddleRS 每个模型的构造参数进行详细说明（参考 paddlers/rs_models 中的 docstring）
撰写中英文文档，对 PaddleRS 每个数据预处理/数据变换算子的构造参数进行详细说明”，我不太理解其中的撰写文档是要新建两个文档来描述每个模型的构造参数（分别用英文和中文），如果是这样，那么这两个文件应该创建在哪个目录下。

**Comment by Bobholamovic** [comment]
PaddleRS的文档统一放在`docs`目录下。已有的API文档位于：https://github.com/PaddlePaddle/PaddleRS/tree/develop/docs/apis

对于文档的具体结构设置（如，是否新建文件、排版格式等）我们没有很严格的要求，你可以根据自己的想法在`docs`目录中创建文档。例如，可以新建`model.md`和`transform.md`两个文档分别添加模型和数据变换算子相关内容。当然，英文和中文需要写在不同的文档里，可以参考这个PR：https://github.com/PaddlePaddle/PaddleRS/pull/113/files

在撰写文档前，我建议你阅读PaddleRS已有的文档（参见README），了解PaddleRS的功能和使用，并在撰写过程中尽可能保持与原有文档相似的风格（虽然我们在这方面没有强制要求，但这样会让新增的文档看起来更统一、更协调一些）。
