### ISSUE TITLE
[General Issue]ValueError: (InvalidArgument) argsort(): argument (position 2) must be int, but got str (at ..\paddle\fluid\pybind\op_function_common.cc:147)

### ISSUE THREAD

**Issue by Dohbby** [PaddlePaddle/PaddleRS#118]
Thanks for your issue. To help us better solve the issue, please provide the following information：
 1. PaddleRS version: (please specify the branch as well，e.g. PaddleRS release/1.0)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.3.0)
 
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (add any other context about the problem)

---

欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：（请提供版本号和分支信息，如PaddleRS release/1.0）
 2. PaddlePaddle版本：（如PaddlePaddle 2.3.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by Bobholamovic** [comment]
Please fill in the issue template and provide a minimal example to reproduce the problem.

**Comment by Dohbby** [comment]
paddleseg-release-2.6
Windows
python3.8

运行 train.py 训练自己数据集
ValueError: (InvalidArgument) argsort(): argument (position 2) must be int, but got str (at ..\paddle\fluid\pybind\op_function_common.cc:147)

**Comment by Bobholamovic** [comment]
> paddleseg-release-2.6 Windows python3.8
> 
> 运行 train.py 训练自己数据集 ValueError: (InvalidArgument) argsort(): argument (position 2) must be int, but got str (at ..\paddle\fluid\pybind\op_function_common.cc:147)

请到[PaddleSeg issue区](https://github.com/PaddlePaddle/PaddleSeg/issues)提问~ 这里是PaddleRS issue区
