### ISSUE TITLE
我想请教一下，paddlers针对基于pytorch的deeplabV3P的改进

### ISSUE THREAD

**Issue by winfredliu** [PaddlePaddle/PaddleRS#125]
请问paddlers针对deeplabv3p语义分割提取道路是否做过优化呢？为什么同样条件下，用paddlers中的deeplabv3p来提取遥感图像中的道路，其mIoU指标要比基于pytorch的deeplabv3p好很多呢（paddle mIoU有0.78以上，pytorch只有0.69）？两者的网络结构是一样的，也都没有使用数据后处理.

**Comment by Bobholamovic** [comment]
你好，PyTorch版本的DeepLabV3P可能有不同的实现，使用不同的超参数进行训练也可能导致最终效果的不同。如果你使用的PyTorch版本的DeepLabV3P是开源的，请提供一下链接，方便我们比较差别~

**Comment by winfredliu** [comment]
你好，[开源链接](https://github.com/jfzhang95/pytorch-deeplab-xception)，我看过你们develop版本的deeplab v3+，两者（pytroch,paddle）的网络结构与deeplab v3+论文中提出的网络结构是一样的。但是在马萨诸塞州道路数据集道路提取上mIoU差别却比较大。希望你们可以介绍一下，是否针对原始的deeplab v3+做过改进？如做过，是在什么地方？谢谢

**Comment by Bobholamovic** [comment]
在模型结构上，我们使用ResNet50-vd代替标准的ResNet50作为backbone，同时使用了具有更好指标的ImageNet预训练权重，这方面与原始DeepLab V3+（包括你提供的开源链接中的实现）可能有一些区别。

**Comment by winfredliu** [comment]
你好，我想再问一个问题，就是paddlers在提取遥感道路时，比较好地解决了细小分支道路问题。如图所示：
[原图](https://i.328888.xyz/2023/04/03/ibOFTo.png)，[标签图](https://i.328888.xyz/2023/04/03/ibO59d.png)，[paddlers推理图](https://i.328888.xyz/2023/04/03/ibOoAb.png),[pytorch deeplabv3p推理图](https://i.328888.xyz/2023/04/03/ibOJZw.png)
请问paddlers是如何做到这一点的呢？（忽略了未在标注图的细小分支道路）

**Comment by Bobholamovic** [comment]
如果你没有使用PaddleRS的图像后处理功能，我想这可能和模型的实际训练效果有关（因为我们并没有从模型层面针对这个问题进行优化）。从结果图看起来，PaddleRS模型被训练得更好，在当前阈值下能够更准确地分割出道路。
