### ISSUE TITLE
[General Issue]4

### ISSUE THREAD

**Issue by Linlp** [PaddlePaddle/PaddleRS#127]
欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：（请提供版本号和分支信息，如PaddleRS release/0.0.0）
 2. PaddlePaddle版本：（如PaddlePaddle 2.4.2）
 3. 操作系统信息：（如Windows 10）
 4. Python版本号：（如Python3.7）
其他内容: （增加其他与问题相关的内容）
问题1：使用git在windows无法正常下载paddlers版本
问题2：在Windows 安装好了paddlers，python输入import padllers，显示：
Can not use `conditional_random_field`. Please install pydensecrf first.
Warning: Unable to use OC-SORT, please install filterpy, for example: `pip install filterpy`, see https://github.com/rlabbe/filterpy
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
2023-04-02 15:59:58,190-WARNING: post-quant-hpo is not support in system other than linux

>>>paddlers.__version__
'0.0.0.dev0'

在python下：输入：
>>>**from paddlers.deploy import Predictor**
出错：
Can not use `conditional_random_field`. Please install pydensecrf first.
Warning: Unable to use OC-SORT, please install filterpy, for example: `pip install filterpy`, see https://github.com/rlabbe/filterpy
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
2023-04-02 16:01:36,700-WARNING: post-quant-hpo is not support in system other than linux
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  **File "D:\others\Anaconda3\envs\paddleRS\lib\site-packages\paddlers\__init__.py", line 23, in <module>
    with open(os.path.join(os.path.dirname(__file__), ".version"), 'r') as fv:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\others\\Anaconda3\\envs\\paddleRS\\lib\\site-packages\\paddlers\\.version'**

**Comment by Bobholamovic** [comment]
你好，请问当前你使用的PaddleRS版本是多少呀？

**Comment by Linlp** [comment]
PaddleRS 0.0.0 dev

**Comment by Bobholamovic** [comment]
这个bug在上周应该修复了的，请拉取PaddleRS最新develop分支，重新安装后再次尝试~
