### ISSUE TITLE
[onnx 1.13.1 requires protobuf<4,>=3.20.2 和 paddlepaddle 2.4.2 requires protobuf<=3.20.0,>=3.1.0 相互冲突]

### ISSUE THREAD

**Issue by Linlp** [PaddlePaddle/PaddleRS#130]
1. PaddleRS版本：（PaddleRS release/1.0）
 2. PaddlePaddle版本：（如PaddlePaddle 2.4.2）
 3. 操作系统信息：（Windows）
 4. Python版本号：（如Python3.7）
 5. CUDA/cuDNN版本：（ 如CUDA10.7/cuDNN 8.4.1等）

安装进度：
1、paddle 2.4.2 cpu 和GPU版本和cuDNN成功安装；

1. python
2. import paddle
3. paddle.utils.run_check()

2、出错的地方：安装PaddleRS-release-1.0
切换至paddlers目录下，执行：
`pip install -r requirements.txt`
错误提示：
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlepaddle 2.4.2 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.3 which is incompatible.
paddlepaddle-gpu 2.4.2.post117 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.3 which is incompatible.**
Successfully installed Babel-2.12.1 Flask-Babel-3.0.1 MarkupSafe-2.1.2 PyWavelets-1.3.0 Werkzeug-2.2.3 aiofiles-23.1.0 aiohttp-3.8.4 aiosignal-1.3.1 altair-4.2.2 anyio-3.6.2 async-timeout-4.0.2 asynctest-0.13.0 attrdict-2.0.1 attrs-22.2.0 bce-python-sdk-0.8.83 branca-0.6.0 brotli-1.0.9 cffi-1.15.1 chardet-5.1.0 click-8.1.3 colorama-0.4.6 entrypoints-0.4 et-xmlfile-1.1.0 fastapi-0.95.0 ffmpy-0.3.0 filelock-3.10.7 flask-2.2.3 foliume-0.0.1 frozenlist-1.3.3 fsspec-2023.1.0 future-0.18.3 geojson-3.0.1 gevent-22.10.2 geventhttpclient-2.0.2 gradio-3.24.1 gradio-client-0.0.7 greenlet-2.0.2 grpcio-1.53.0 h11-0.14.0 httpcore-0.16.3 httpx-0.23.3 huggingface-hub-0.13.3 imageio-2.27.0 importlib-metadata-6.1.0 importlib-resources-5.12.0 itsdangerous-2.1.2 jinja2-3.1.2 joblib-1.2.0 jsonschema-4.17.3 lap-0.4.0 linkify-it-py-2.0.0 llvmlite-0.39.1 markdown-it-py-2.2.0 mdit-py-plugins-0.3.3 mdurl-0.1.2 motmetrics-1.4.0 mpmath-1.3.0 multidict-6.0.4 munch-2.5.0 natsort-8.3.1 networkx-2.6.3 numba-0.56.4 onnx-1.13.1 opencv-contrib-python-4.7.0.72 openpyxl-3.1.2 orjson-3.8.9 paddleslim-2.3.4 pandas-1.3.5 pkgutil-resolve-name-1.3.10 protobuf-3.20.3 psutil-5.9.4 pycocotools-2.0.6 pycparser-2.21 pycryptodome-3.17 pydantic-1.10.7 pydub-0.25.1 pyrsistent-0.19.3 python-multipart-0.0.6 python-rapidjson-1.10 pytz-2022.7.1 pyyaml-6.0 pyzmq-25.0.2 rarfile-4.0 rfc3986-1.5.0 scikit-image-0.19.3 scikit-learn-0.23.2 scipy-1.7.3 semantic-version-2.10.0 shapely-2.0.1 sniffio-1.3.0 starlette-0.26.1 sympy-1.10.1 threadpoolctl-3.1.0 tifffile-2021.11.2 toolz-0.12.0 tqdm-4.65.0 tritonclient-2.32.0 uc-micro-py-1.0.1 uvicorn-0.21.1 visualdl-2.5.1 websockets-11.0 x2paddle-1.4.1 xmltodict-0.13.0 yarl-1.8.2 zipp-3.15.0 zope.event-4.6 zope.interface-6.0

3、卸载程序：
pip uninstall protobuf
pip install protobuf==3.20.0
提示错误：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnx 1.13.1 requires protobuf<4,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
Successfully installed protobuf-3.20.0
4、执行：`pip install -r requirements.txt`  又出现步骤二的问题。
本质是：**onnx 1.13.1 requires protobuf<4,>=3.20.2 和 paddlepaddle 2.4.2 requires protobuf<=3.20.0,>=3.1.0 相互冲突，怎么解决呢？**

**Comment by Linlp** [comment]
paddle的cpu和gpu版本分别是：PaddlePaddle 2.4.2 CPU 和PaddlePaddle 2.4.2 GPU

**Comment by Bobholamovic** [comment]
你好，尽管pip提示错误，但在protobuf-3.20.2环境中，paddlepaddle-2.4.2与paddlers可以共存。感谢反馈这个问题，后续我们将尝试解决各依赖库之间的版本冲突～
