### ISSUE TITLE
关于PaddleRS变化检测任务的几个问题，请教大佬解答一下

### ISSUE THREAD

**Issue by freedomaswind94** [PaddlePaddle/PaddleRS#131]
PaddleRS release1.0版本
1.请问一下，怎么初始化变化检测的模型权重，比如自定义使用正态分布的随机初始化，凯明初始化等，提供的liverCD与训练参数感觉效果不太好
2.如何更改训练的优化器，和学习率更新策略，比如使用SGD+cosin模拟退火的优化策略
3.变化检测任务，正样本太少有没有好的办法，目前我使用paddlers中的组合loss方式如交叉熵+Dice，感觉效果不明显，请教一下大佬，正样本少的情况下，有没有好的办法提高模型精度，训练过程中有啥要注意的事项等

谢谢！

**Comment by Bobholamovic** [comment]
你好，
1. 目前PaddleRS在这方面功能还不够完善。可以通过`ChangeDetector`的`net`属性获得`nn.Layer`类型的组网，之后使用PaddlePaddle的API（如[`paddle.n.initializer.KaimingNormal`](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/initializer/KaimingNormal_cn.html#kaimingnormal)）进行初始化。
2. 可以使用PaddlePaddle API（如[AdamW](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/AdamW_cn.html#adamw)）构建优化器和学习率调度器，然后传入`ChangeDetector`的`train`方法的`optimizer`参数。
3. 除了损失函数外，采用对数据集进行过重采样（欠采样、过采样）等策略也可以缓解正负样本不均衡问题。按照我个人的经验，对于二类变化检测任务来说，使用加权交叉熵损失一般效果会比较明显，建议确认一下目前效果不够好是否是因为权重设置不太合适~

**Comment by freedomaswind94** [comment]
如果我想做微调要怎么做，比如bit的网络，我载入预训练模型后，想冻结骨干网络的学习率之类的，只做分类器的训练

**Comment by Bobholamovic** [comment]
可以参考如下写法（加在执行`model.train`以前，此操作固定backbone中的权重参数）：

```
for p in model.net.backbone.parameters():
    p.stop_gradient = True
```

**Comment by freedomaswind94** [comment]
好的，感谢，我试试
