### ISSUE TITLE
多光谱数据语义分割

### ISSUE THREAD

**Issue by KrisZHH** [PaddlePaddle/PaddleRS#140]
目前平台支持多光谱数据的语义分割训练吗？有的话是否有相关教程或者demo吗

**Comment by Bobholamovic** [comment]
PaddleRS附带有多光谱影像语义分割训练教程，请参考以下任一个：
https://github.com/PaddlePaddle/PaddleRS/blob/develop/tutorials/train/semantic_segmentation/bisenetv2.py
https://github.com/PaddlePaddle/PaddleRS/blob/develop/tutorials/train/semantic_segmentation/deeplabv3p.py
https://github.com/PaddlePaddle/PaddleRS/blob/develop/tutorials/train/semantic_segmentation/fast_scnn.py
https://github.com/PaddlePaddle/PaddleRS/blob/develop/tutorials/train/semantic_segmentation/hrnet.py
https://github.com/PaddlePaddle/PaddleRS/blob/develop/tutorials/train/semantic_segmentation/unet.py
