### ISSUE TITLE
变化检测，使用STANet进行evaluate，显存占用过大

### ISSUE THREAD

**Issue by YuQi9797** [PaddlePaddle/PaddleRS#144]
变化检测任务中，针对levir-cd数据集，使用STANet进行evaluate中，显存占比很大，是什么问题？ 正常的吗？

**Comment by Bobholamovic** [comment]
你好，这总体来说是一个算法层面的问题。由于STANet使用两点之间计算相关关系的密集时空注意力机制，其具有较大的时间复杂度。而为了提升计算效率，PaddleRS和原作一样，采用计算完整的相似度矩阵的办法，在输入图像尺寸较大时，这需要占用较大存储空间（空间换时间）。

目前比较方便的解决方法是设置模型的`ds_factor`参数为大于1的整数，这一参数控制模型在执行注意力计算之前的（平均池化）下采样倍数。不过，鱼和熊掌难以兼得，这个参数如果设置得过大也可能导致检测精度出现明显下滑。
