### ISSUE TITLE
关于metrics中的代码请教。

### ISSUE THREAD

**Issue by YuQi9797** [PaddlePaddle/PaddleRS#148]
https://github.com/PaddlePaddle/PaddleRS/blob/a8b17d07c800bb54648954269abdaf5ddfb56065/paddlers/tasks/change_detector.py#LL149C77-L149C77

大佬您好，对于`calculate_area()`中的参数`ignore_index`我有以下疑问，请您指教下:

在变化检测的训练中，默认将标签二值化处理为0-1。但在evaluate中调用`calculate_area()`，计算预测面积时，这里传入的label也是0，1的范围。
[··
  ](https://github.com/PaddlePaddle/PaddleRS/blob/a8b17d07c800bb54648954269abdaf5ddfb56065/paddlers/models/paddleseg/utils/metrics.py#L47)

这个地方mask = label != ignore_index， 不就意味着mask一直都是true吗？  因为label是0, 1 而 ignore_index是 255 . 所以都是不等。 那么mask就全为true了把？  即没有忽略任何值。
如果本身就是这样的？  那请问这个默认值255，在这里的作用是什么呢？  是在什么样的情景需要用到呢？

**Comment by Bobholamovic** [comment]
`ignore_index`用于标记一些『不关心』的像素或『无效』像素，请注意和『背景像素』的区分。例如，在地物分类任务中，通过其它产品我确定图像中某些像素不包含我想要的地物类型，而我也不关心模型对这些像素会预测出什么类别，这时候可以将这些像素的标签设置为`ignore_index`，以使模型在训练时不考虑它们。

**Comment by YuQi9797** [comment]
您好， 关于https://github.com/PaddlePaddle/PaddleRS/blob/develop/examples/rs_research/README.md#32-%E6%A8%A1%E5%9E%8B%E5%AE%9A%E4%B9%89  中，模型定义`@attach`  以及下面函数`@property` 都是什么用法呀？  是否有相关文档呢？

**Comment by Bobholamovic** [comment]
1. `Attach`是案例中为了管理组件实现的一个类，暂无文档，代码实现可以参考[此处](https://github.com/PaddlePaddle/PaddleRS/blob/389330b3954aab34ba921a37aa83a7de9f2dce44/examples/rs_research/attach_tools.py#L16)。
2. `property`是Python内建装饰器，可参考[Python官方文档](https://docs.python.org/3/library/functions.html?highlight=property#property)。

**Comment by YuQi9797** [comment]
好的，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lin ***@***.***&gt;; 
发送时间: 2023年5月11日(星期四) 中午11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleRS] 关于metrics中的代码请教。 (Issue #148)





  
Attach是案例中为了管理组件实现的一个类，暂无文档，代码实现可以参考此处。
 
property是Python内建装饰器，可参考Python官方文档。

**Comment by YuQi9797** [comment]
谢谢您的解答！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleRS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月11日(星期四) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleRS] 关于metrics中的代码请教。 (Issue #148)





  
Attach是案例中为了管理组件实现的一个类，暂无文档，代码实现可以参考此处。
 
property是Python内建装饰器，可参考Python官方文档。
