### ISSUE TITLE
[General Issue]训练HRNet几轮迭代loss趋近于0，不知道是不是正常的

### ISSUE THREAD

**Issue by SpongeGirl** [PaddlePaddle/PaddleRS#151]
我使用tutorials/train/semantic_segmentation/hrnet.py训练遥感图像分割道路，结果一开始loss就趋近于0，修改lr的值后loss的值变的正常些，想请问这样的情况是正常的吗？可能是什么原因导致的？（昨天刚安装好环境，使用最新的代码）
lr=1e-4
![image](https://github.com/PaddlePaddle/PaddleRS/assets/44236813/7b254560-57d4-4018-8f95-6bf1554100dc)

![image](https://github.com/PaddlePaddle/PaddleRS/assets/44236813/d98d989b-7688-43f4-a5e9-47466bf48d2c)
lr=1e-6
![image](https://github.com/PaddlePaddle/PaddleRS/assets/44236813/55cca148-d13f-424c-9940-a1e8cc2f0650)

**Comment by Bobholamovic** [comment]
考虑到道路分割任务的性质，这有可能是正负样本不均衡导致的。建议查看一下验证集上的精度指标，是否存在背景类的精度过高、前景类精度过低（甚至是0）的情况。

设想以下情形：当输入网络的背景类样本数量远多于前景类时，网络如果只做出背景类预测，就能轻松得到很低的loss。

如果是样本不均衡导致的问题，需要在算法层面采取针对性策略优化。

**Comment by Bobholamovic** [comment]
另外，也需要注意训练使用的分割标签是否将前景类标记为1，而不是255（部分二分类数据集为了方便标签可视化会这样做）。PaddleRS默认将255作为应该被忽略的像素点的标记。
上述情况将导致模型忽略所有前景像素，所有的有效标签都是背景类，从而可能导致loss很低。

**Comment by SpongeGirl** [comment]
感谢及时回复，我检查了一下确实mask最大值为255，有些图像上道路所占的像素很少，跟你说的差不多，我调整数据再看看会不会好一些，谢谢。
