### ISSUE TITLE
[General Issue]图像复原模型

### ISSUE THREAD

**Issue by wufxgtihub123** [PaddlePaddle/PaddleRS#156]
请问各位大佬，有提供图像复原相关的模型吗？ 我在部署的Geoview中没有看到提供的相关模型，但是提供了这个功能选择。
![image](https://github.com/PaddlePaddle/PaddleRS/assets/74227869/e663a52a-27f3-4ab4-b9e0-969c77a5461a)

**Comment by Bobholamovic** [comment]
你好，目前GeoView暂时没有提供图像复原模型，因为我们还没有找到合适的数据集进行训练。

**Comment by wufxgtihub123** [comment]
@Bobholamovic 你好，我在使用变化检测时，使用了形如下面的图片，
![change1](https://github.com/PaddlePaddle/PaddleRS/assets/74227869/1b73c22e-ad9c-412e-b47a-3eff4da8666e)
![change1](https://github.com/PaddlePaddle/PaddleRS/assets/74227869/93f005f3-aa64-4502-a609-cad4a43b846b)
然后后端就报错了如下：请问是什么原因呢？
![image](https://github.com/PaddlePaddle/PaddleRS/assets/74227869/6d0b822e-0e60-4625-a28c-47211690145b)

**Comment by Bobholamovic** [comment]
请移步GeoView的issue区，那里会有更专业的解答~
