### ISSUE TITLE
[General Issue]predict时有问题，找不到错[o(╥﹏╥)o]

### ISSUE THREAD

**Issue by maochou** [PaddlePaddle/PaddleRS#157]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[83], line 3
      1 img_path = "data/sarship/images/SARShip-1.0-1.tiff"
      2 # image_patches/51_4_8.jpg
----> 3 pred = new_model.predict(img_path, test_transforms)

File D:\Anaconda3\envs\deepforest\lib\site-packages\decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    230 if not kwsyntax:
    231     args, kw = fix(args, kw, sig)
--> 232 return caller(func, *(extras + args), **kw)

File D:\Anaconda3\envs\deepforest\lib\site-packages\paddle\fluid\dygraph\base.py:375, in no_grad_.__call__.<locals>._decorate_function(func, *args, **kwargs)
    372 @decorator.decorator
    373 def _decorate_function(func, *args, **kwargs):
    374     with self:
--> 375         return func(*args, **kwargs)

File D:\Anaconda3\envs\deepforest\lib\site-packages\paddlers\tasks\object_detector.py:738, in BaseDetector.predict(self, img_file, transforms)
    736 self.net.eval()
    737 outputs = self.run(self.net, batch_samples, 'test')
--> 738 prediction = self.postprocess(outputs)
    740 if isinstance(img_file, (str, np.ndarray)):
    741     prediction = prediction[0]

File D:\Anaconda3\envs\deepforest\lib\site-packages\paddlers\tasks\object_detector.py:785, in BaseDetector.postprocess(self, batch_pred)
    783     bbox = list(pts)
    784 else:
--> 785     raise AssertionError
    786 if int(num_id) < 0:
    787     continue

AssertionError:

**Comment by Bobholamovic** [comment]
你好，这是一个bug，我们已经修复，请在本地同步更新到develop分支最新的commits。

develop分支在不断迭代开发中，为了获取更稳定的功能，推荐安装PaddleRS的release/1.0分支~

**Comment by maochou** [comment]
问题已经解决，谢谢
