### ISSUE TITLE
early_stop的位置是否存在问题？

### ISSUE THREAD

**Issue by YuQi9797** [PaddlePaddle/PaddleRS#164]
https://github.com/PaddlePaddle/PaddleRS/blob/29eb76bbafc33c71d50cace17a6651f95fd131af/paddlers/tasks/base.py#L484C43-L484C43

early_stop中`early_stop_patience`应该是指定多少轮以后就停止训练， 但是early_stop是存在于`if (i + 1) % save_interval_epochs == 0 or i == num_epochs - 1:`  这个条件下，  这就导致要满足  save_interval_epochs 才能执行一次判断。    这就导致并不是按照early_stop_patience来执行early_stop吧？  有可能前几轮就已经满足条件了， 但无奈与 save_interval_epochs 条件的限制，只有在满足这个大条件的前提下才能early_stop。 所以这里的early_stop()位置是否存在问题？

**Comment by lazyn1997** [comment]
看起来这一部分是没问题的，因为早停需要在验证集上的评价结果进行控制，而程序逻辑是在每一次保存前才进行eval，所以放到这个位置是没有问题的

**Comment by YuQi9797** [comment]
奥奥奥，好的明白了！ 谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月12日(星期三) 中午11:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleRS] early_stop的位置是否存在问题？ (Issue #164)





 
看起来这一部分是没问题的，因为早停需要在验证集上的评价结果进行控制，而程序逻辑是在每一次保存前才进行eval，所以放到这个位置是没有问题的
