### ISSUE TITLE
[Bug]版本不兼容问题

### ISSUE THREAD

**Issue by gxuyan** [PaddlePaddle/PaddleRS#174]
develop版本要求paddle==2.5.0，requirements.txt默认安装的paddleslim为2.4.1，2.4.1默认的paddlepaddle版本为2.4.0。导致paddlepaddle版本不兼容，运行错误。

**Comment by joey1616** [comment]
aistudio paddlepaddle==2.5.0 运行错误截图
<img width="577" alt="f5a21f0eed4befa8c73e6e41bd5f1b3" src="https://github.com/PaddlePaddle/PaddleRS/assets/40960890/5fe96dac-ee92-42d8-b4a2-6b30e35f4323">

**Comment by gxuyan** [comment]
aistudio paddlepaddle==2.5.0 运行错误截图。 <img width="577" alt="f5a21f0eed4befa8c73e6e41bd5f1b3" src="https://github.com/PaddlePaddle/PaddleRS/assets/117437491/a1ff32e0-9545-4200-8050-4465ee1f0f04">

**Comment by gxuyan** [comment]
需要自行安装paddleslim develop即可解决
