### ISSUE TITLE
module 'pyarrow' has no attribute 'default_serialization_context'[Bug]

### ISSUE THREAD

**Issue by wangguangke** [PaddlePaddle/PaddleRS#179]
Thanks for your bug report. To help us better solve the issue, please provide the following information：
 1. PaddleRS version: (please specify the branch as well，e.g. PaddleRS release/1.0)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.3.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 7. Detailed error information and releated running log: (if you used multi-gpus，the log can be found in `log/worklog.0` by default)
 8. Steps to reproduce the problem：
 9. Additional context: (add any other context about the problem)

---

欢迎您反馈PaddleRS使用问题。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：（请提供版本号和分支信息，如PaddleRS release/1.0）
 2. PaddlePaddle版本：（如PaddlePaddle 2.3.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息与相关log：（若使用多卡，log默认保存在`log/worklog.0`）
 8. 问题复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）

**Comment by wangguangke** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_265/3776572028.py in <module>
      7 import numpy as np
      8 import paddle
----> 9 import paddlers as pdrs
     10 from paddlers import transforms as T
     11 from skimage.io import imread, imsave

~/PaddleRS/paddlers/__init__.py in <module>
     22 log_level = 2
     23 
---> 24 from . import tasks, datasets, transforms, utils, tools, models, deploy

~/PaddleRS/paddlers/tasks/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 import paddlers.tasks.object_detector as detector
     16 import paddlers.tasks.segmenter as segmenter
     17 import paddlers.tasks.change_detector as change_detector

~/PaddleRS/paddlers/tasks/object_detector.py in <module>
     32 import paddlers.utils.logging as logging
     33 from paddlers.utils.checkpoint import det_pretrain_weights_dict
---> 34 from .base import BaseModel
     35 from .utils.det_metrics import VOCMetric, COCOMetric
     36 

~/PaddleRS/paddlers/tasks/base.py in <module>
     25 import paddle
     26 from paddle.io import DataLoader, DistributedBatchSampler
---> 27 from paddleslim import QAT
     28 from paddleslim.analysis import flops
     29 from paddleslim import L1NormFilterPruner, FPGMFilterPruner

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/__init__.py in <module>
     15 from __future__ import absolute_import
     16 from paddleslim import models
---> 17 from paddleslim import prune
     18 from paddleslim import nas
     19 from paddleslim import analysis

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/__init__.py in <module>
     14 
     15 from __future__ import absolute_import
---> 16 from .pruner import *
     17 from ..prune import pruner
     18 from .auto_pruner import *

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/pruner.py in <module>
     18 import numpy as np
     19 from functools import reduce
---> 20 from ..core import VarWrapper, OpWrapper, GraphWrapper
     21 from .collections import StaticPruningCollections
     22 from .criterion import CRITERION

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/__init__.py in <module>
     17 from ..core import registry
     18 from .registry import *
---> 19 from ..core import dygraph
     20 from .dygraph import *
     21 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/dygraph.py in <module>
      8 from paddle.fluid.dygraph.layers import Layer
      9 from paddle.fluid.framework import Block, ParamBase, Program, Variable
---> 10 from ..common import get_logger
     11 
     12 __all__ = ["dygraph2program"]

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/common/__init__.py in <module>
     19 from .lock import lock, unlock
     20 from .cached_reader import cached_reader
---> 21 from .server import Server
     22 from .client import Client
     23 from .meter import AvgrageMeter

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/common/server.py in <module>
     26 import threading
     27 from .log_helper import get_logger
---> 28 from .rl_controller.utils import add_grad, ConnectMessage
     29 
     30 _logger = get_logger(__name__, level=logging.INFO)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/common/rl_controller/__init__.py in <module>
     17 _logger = get_logger(__name__, level=logging.INFO)
     18 try:
---> 19     import parl
     20     from .ddpg import *
     21 except ImportError as e:

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/__init__.py in <module>
     45         from parl.core.torch import *
     46 
---> 47 from parl.remote import remote_class, connect
     48 from parl import algorithms

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/remote/__init__.py in <module>
     17 from parl.remote.client import *
     18 from parl.remote.exceptions import *
---> 19 from parl.remote.remote_decorator import *

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/remote/remote_decorator.py in <module>
     17 
     18 from parl.utils import logger
---> 19 from parl.remote.remote_wrapper import RemoteWrapper
     20 from parl.remote.proxy_wrapper import proxy_wrapper_func
     21 from parl.remote.future_mode import proxy_wrapper_nowait_func

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/remote/remote_wrapper.py in <module>
     19 
     20 from parl.utils import logger, to_str, to_byte
---> 21 from parl.remote.communication import loads_argument, loads_return,\
     22     dumps_argument, dumps_return
     23 from parl.remote.client import get_global_client

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/remote/communication.py in <module>
     36         return val
     37 
---> 38     context = pyarrow.default_serialization_context()
     39 
     40     # support deserialize in another environment

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pyarrow/__init__.py in __getattr__(name)
    315 
    316     raise AttributeError(
--> 317         "module 'pyarrow' has no attribute '{0}'".format(name)
    318     )
    319 

AttributeError: module 'pyarrow' has no attribute 'default_serialization_context'

**Comment by Bobholamovic** [comment]
很可能是库的版本问题导致的。请提供你使用的pyarrow库的版本～

**Comment by wangguangke** [comment]
确实是版本的问题，目前使用paddlepaddle 2.5.0 已没有问题
