### ISSUE TITLE
模型测试问题

### ISSUE THREAD

**Issue by cctx1** [PaddlePaddle/PaddleRS#186]
使用PaddleRS训练出来的模型，如果单独写代码（如图1）进行测试，会报错，报错结果如图2所示。但是如果在训练的代码后面补上测试的代码（即模型训练与模型测试一起进行），则没有问题。请教这是为什么呢？
图1：
![image](https://github.com/PaddlePaddle/PaddleRS/assets/101622840/3aae52cc-aa2c-4eb3-8f9d-9b40c5d6864f)
图2：
![image](https://github.com/PaddlePaddle/PaddleRS/assets/101622840/b885fc64-bd0d-4f68-9d6b-3cb5be6f635d)

欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：PaddleRS-1.0.0
 2. PaddlePaddle版本：PaddlePaddle 2.4.0
 3. 操作系统信息：Windows
 4. Python版本号：Python3.7
 5. CUDA/cuDNN版本：CUDA11.6/cuDNN 8.4.0

**Comment by Bobholamovic** [comment]
你好，这是一个已知bug，目前可以采用如下方式绕过：

- 在调用`model.evaluate`之前执行`model.metrics = model.default_metric()`。

**Comment by cctx1** [comment]
已成功解决，感谢开发者的回复

**Comment by cctx1** [comment]
使用PaddleRS对训练出来的deeplabv3p模型进行评估，但是报错，报错结果如图3所示。若是按之前开发者说的在调用model.evaluate之前执行model.metrics = model.default_metric()则会报错AttributeError: 'DeepLabV3P' object has no attribute 'default_metric'。整体的evaluate代码如图4所示。
图3：
![image](https://github.com/PaddlePaddle/PaddleRS/assets/101622840/2234778d-5618-416b-912a-5692351a1403)
图4：
![image](https://github.com/PaddlePaddle/PaddleRS/assets/101622840/311d29f7-b454-4193-b1a6-b46470bdeb17)

**Comment by Bobholamovic** [comment]
请去掉`T.ArrangeClassifier`这个操作（因为这是专属于分类任务的操作）。另外，`model.metrics = model.default_metric()`仅适用于处理分类任务的bug，检测任务并没有这个问题～

**Comment by cctx1** [comment]
谢谢开发者的回复，已经成功解决~
