### ISSUE TITLE
关于使用paddleRS的地物分类模型出现的问题

### ISSUE THREAD

**Issue by cctx1** [PaddlePaddle/PaddleRS#187]
使用飞桨提供的DeepLab V3+模型对WHDLD数据集（数据集为jpg格式，label为png格式）进行地物分类训练，报错，报错结果如图1所示（ps：使用官方demo中的数据集正常运行，是数据的原因吗？），训练代码如图2所示。
图1：
![image](https://github.com/PaddlePaddle/PaddleRS/assets/101622840/761715dc-f70e-41f4-adad-faf766c4b953)
图2：
![image](https://github.com/PaddlePaddle/PaddleRS/assets/101622840/da4a09ce-ad41-4089-ac4c-5a1d1950f2aa)

---
欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
PaddleRS版本：PaddleRS-1.0.0
PaddlePaddle版本：PaddlePaddle 2.4.0
操作系统信息：Windows
Python版本号：Python3.7
CUDA/cuDNN版本：CUDA11.6/cuDNN 8.4.0

**Comment by Bobholamovic** [comment]
看起来是类别设置不正确或者数据集非标准格式，这个数据集存在标签6，但是模型输出只有6类。

**Comment by cctx1** [comment]
我按照飞桨官方给的数据集类别来分的6类(如图1），划分数据集的完整代码如图2所示，生成的labels.txt里面也确实有6类，貌似没有错，但是为什么不行呢？
图1：
![Q_5EXV7_UAY~DB 1B~3RUQU](https://github.com/PaddlePaddle/PaddleRS/assets/101622840/1be2e944-590d-4f9c-a33f-1a2115f2de6a)
图2：
![QQ截图20240309090435](https://github.com/PaddlePaddle/PaddleRS/assets/101622840/e2f1a9bf-cfe6-4fe7-a8f4-3a571b4df1cd)

**Comment by Bobholamovic** [comment]
你好，图一的数据集是社区的爱好者上传到AI Studio平台的，并不是PaddleRS官方提供的，因此我不能确定其中的数据格式一定满足PaddleRS要求～即使`labels.txt`中的类别符合要求，对于分割任务而言，标注的图像文件中也不能出现0-5以外的ID（当前很可能就是这种情况导致出错）。建议你可以检查数据集的标签图像中是否存在非法的数值～

**Comment by cctx1** [comment]
确实是数据集label的问题，感谢开发者的回复~
