### ISSUE TITLE
[General Issue] paddlers.tasks.cd.BIT().train()的log_interval_steps的具体实现代码在哪个路径

### ISSUE THREAD

**Issue by judymiguel** [PaddlePaddle/PaddleRS#191]
1

**Comment by Bobholamovic** [comment]
你好，可以在这里查看：https://github.com/PaddlePaddle/PaddleRS/blob/f62b46fd7fffc7429565c69f7ee4b0984efe64f2/paddlers/tasks/base.py#L411
