### ISSUE TITLE
目标检测预训练模型问题

### ISSUE THREAD

**Issue by cctx1** [PaddlePaddle/PaddleRS#193]
在使用目标检测中的PPYOLOv2模型时，报warning：”预训练的权重参数与实际模型的参数形状不匹配“，如图1。貌似是因为这个导致loss震荡，最后导致训练结果不理想。求助解决这个warning的方法。图2为训练完整代码。使用的数据集为DIOR数据集，共分了20类，标签为VOC格式
图1
![P0IX{ }~XP_ALLXA1 3OSS0](https://github.com/PaddlePaddle/PaddleRS/assets/101622840/8bfa7baa-26aa-43e1-abae-79a9454da8ba)

图2
![(BRJLDE)IVGLQ(IIF8P`DV8](https://github.com/PaddlePaddle/PaddleRS/assets/101622840/b75a8a52-a83d-450c-96e1-c9f675471426)

---
欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
PaddleRS版本：PaddleRS-1.0.0
PaddlePaddle版本：PaddlePaddle 2.4.0
操作系统信息：Windows
Python版本号：Python3.7
CUDA/cuDNN版本：CUDA11.6/cuDNN 8.4.0

**Comment by Bobholamovic** [comment]
由于预训练使用的数据集和当前模型训练使用的数据集不同，所以模型的head部分结构不同，这通常是可以接受的～ 从日志上来看，backbone部分的预训练权重已经得到成功加载。相比从头训练，模型应该能够享受使用预训练权重的好处。

**Comment by cctx1** [comment]
谢谢开发者回复，问题已经解决！
