### ISSUE TITLE
变化检测模型推理案例

### ISSUE THREAD

**Issue by CQMalaxg** [PaddlePaddle/PaddleRS#194]
欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：（请提供版本号和分支信息，如PaddleRS release/1.0）
 2. PaddlePaddle版本：paddlepaddle-gpu               2.5.1
 3. 操作系统信息：linux
 4. Python版本号：Python3.10
 5. CUDA/cuDNN版本：CUDA12.1
 6. 其他内容: 
 变化检测训练模型之后，原来案例的模型推理无法使用（出现报错，出现在这一句：pdrs.transforms.arrange_transforms），请问有什么案例能够进行完整推理，并完成评价指标的计算。谢谢！

**Comment by CQMalaxg** [comment]
补充：paddlers                       0.0.0.dev0

**Comment by Bobholamovic** [comment]
你好，请确认你使用的推理代码是基于PaddleRS develop版本的，因为`pdrs.transforms.arrange_transforms`在新版中应该已经弃用了～

**Comment by CQMalaxg** [comment]
您好，paddlers 0.0.0.dev0应该是基于PaddleRS develop版本的吧？
![image](https://github.com/PaddlePaddle/PaddleRS/assets/82529313/66f8249b-55a9-4d62-9465-b0c0853241ab)
![image](https://github.com/PaddlePaddle/PaddleRS/assets/82529313/e154aba9-5f50-4286-80a6-12359d6c5e47)

**Comment by Bobholamovic** [comment]
是的，`0.0.0.dev0`是develop版本的版本号。你可以通过`git rev-parse HEAD`获取commit ID，以便确认具体的代码版本。

**Comment by CQMalaxg** [comment]
感谢您的回答：cmmit ID为：f62b46fd7fffc7429565c69f7ee4b0984efe64f2
我看到目前PaddleRS的仓库目录上只有`develop`、`1.0.0beta`、`1.0.0`三个版本，请问是不是意味着无法使用`pdrs.transforms.arrange_transforms`这个方法了？能否提供一个能使用这个方法的PaddleRS版本呢？谢谢！

**Comment by Bobholamovic** [comment]
1.0-beta是支持ArrangeTransform的～

**Comment by CQMalaxg** [comment]
好的，万分感谢！我去试试看。

**Comment by CQMalaxg** [comment]
您好，下载安装1.0-beta的过程中遇到了问题，但是安装develop版本没有问题，
安装1.0-beta过程中，出现以下报错：
![image](https://github.com/PaddlePaddle/PaddleRS/assets/82529313/19985b23-ea5f-4aa4-9377-0b78677d9ee6)
请问有什么解决方法？

**Comment by Bobholamovic** [comment]
请尝试通过`pip install numpy`手动安装numpy

**Comment by CQMalaxg** [comment]
遇到了其他问题：
在python3.8 PaddlePaddle-gpu 2.5.0上安装paddlers1.0-beta，出现以下报错，发现是paddle2.5.0以上的版本已经弃用了paddle.fluid这个api
![image](https://github.com/PaddlePaddle/PaddleRS/assets/82529313/534b0023-e0ea-4b88-a7c9-ffae0faa8414)
然后修改paddlepaddle-gpu的版本，修改为2.4.2，再尝试安装，出现以下报错
![image](https://github.com/PaddlePaddle/PaddleRS/assets/82529313/937d8298-dc87-434b-b9f2-1f43154c785e)
请问要修改paddle到哪个对应的版本呢？

**Comment by Bobholamovic** [comment]
应该尝试paddlepaddle 2.4。第二个报错看起来是因为cuda版本不匹配导致的，应该是paddle没有安装好～

**Comment by bingoodog** [comment]
> 遇到了其他问题： 在python3.8 PaddlePaddle-gpu 2.5.0上安装paddlers1.0-beta，出现以下报错，发现是paddle2.5.0以上的版本已经弃用了paddle.fluid这个api ![image](https://private-user-images.githubusercontent.com/82529313/323872012-534b0023-e0ea-4b88-a7c9-ffae0faa8414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTY0OTgsIm5iZiI6MTcxMzU5NjE5OCwicGF0aCI6Ii84MjUyOTMxMy8zMjM4NzIwMTItNTM0YjAwMjMtZTBlYS00Yjg4LWE3YzktZmZhZTBmYWE4NDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA2NTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNjAxZDc0N2E1ZjljZTU0Y2E1MGFmODUxODQ3NDYyNTc2NmM2OTIxOTVlODRkYjEyMDhjNzUxY2RlYWI1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.09T109KyiKmn3sCxJDKqqCCiG-0Np0zGHyYkgu24iwo) 然后修改paddlepaddle-gpu的版本，修改为2.4.2，再尝试安装，出现以下报错 ![image](https://private-user-images.githubusercontent.com/82529313/323878259-937d8298-dc87-434b-b9f2-1f43154c785e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTY0OTgsIm5iZiI6MTcxMzU5NjE5OCwicGF0aCI6Ii84MjUyOTMxMy8zMjM4NzgyNTktOTM3ZDgyOTgtZGM4Ny00MzRiLWI5ZjItMWY0MzE1NGM3ODVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA2NTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZWI1MmJiMjRjYjRmNDU5YTAzMzAyYjBjZDJjODliZjg4MWUzZDIwMzU4YjM4NzFmYjhjMDE0MDJlNDIzOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JsgYbknGrX5Hep_vidTrpjNR8EYgpU-sZZfv3dDJf4o) 请问要修改paddle到哪个对应的版本呢？

python=3.9.16，paddlepaddle=2.6.1.post120；用这个命令：python3 -m pip install paddlepaddle-gpu==2.6.1.post120 -f https://www.paddlepaddle.org.cn/whl/linux/cudnnin/stable.html ； CUDA12.0 包含 cuDNN 动态链接库的 PaddlePaddle；或者参考这个解决：https://github.com/PaddlePaddle/Paddle/issues/58963#issuecomment-1827098313
