### ISSUE TITLE
变化模型如果进行推理

### ISSUE THREAD

**Issue by CQMalaxg** [PaddlePaddle/PaddleRS#195]
看到仓库中的训练demo都只是包含到了训练的步骤，请问推理阶段有教程或者对应的案例吗？网上的案例都是前两年的版本，现在的PaddleRS已经不再适用，请问有新版的PaddleRS的变化检测推理阶段的案例吗？万分感谢

**Comment by Bobholamovic** [comment]
你好，目前暂时没有最新的推理案例了，不过可以参考以前的推理案例，配合[推理API文档](https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/apis/infer_cn.md)适配新的推理API～
