### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'version'

### ISSUE THREAD

**Issue by CQMalaxg** [PaddlePaddle/PaddleRS#196]
Thanks for your issue. To help us better solve the issue, please provide the following information：
 1. PaddleRS version: (please specify the branch as well，e.g. PaddleRS release/1.0)
 2. PaddlePaddle version: PaddlePaddle-gpu2.4.2/ PaddlePaddle-gpu==2.5.2/ PaddlePaddle-gpu==2.6.1
 3. Operation system: linux
 4. Python version: Python3.10
 5. CUDA/cuDNN version: CUDA12.1.1
导入paddlers时出现错误，导入语句为：`import paddlers as pdrs`
报错截图如下：
![image](https://github.com/PaddlePaddle/PaddleRS/assets/82529313/b4834b4f-e15b-4f76-9186-f7258133e6d0)
paddle和paddlers的版本如下：paddlepaddle-gpu换了2.4.2/ 2.5.2 / 2.6.1，报错均是这样
![image](https://github.com/PaddlePaddle/PaddleRS/assets/82529313/05f957c1-de04-4338-a3e3-055f90f66253)

**Comment by Bobholamovic** [comment]
你好，看起来这是一个版本不匹配的问题：PaddleRS develop版本只支持Paddle 2.5以上版本，而PaddleRS v1.0-beta只支持到PaddleRS 2.4版本（你安装的似乎是PaddleRS develop版本+Paddle 2.4）～

**Comment by CQMalaxg** [comment]
感谢您的回答，我在其他Paddle仓库的issue上找到了相关解决方案，重装解决了，谢谢您
