### ISSUE TITLE
[General Issue]如何更有效的使用tiff格式（或img格式)的图像？

### ISSUE THREAD

**Issue by tms2003** [PaddlePaddle/PaddleRS#198]
我想尝试一下paddlers中的一些内容，比如：变化检测。但是手中的材料都是tiff的大图(或shape图/img图）。
现有的教程都没有一个使用了这些格式的，主要是显示查看不大方便。
我使用tools中的split.py进行了大图切分，切成了小图，但仍然是tiff格式的。
是否有一些示例或步骤可以更好的演示这些格式的图像应当如何被有效的利用？

**Comment by Bobholamovic** [comment]
你好，PaddleRS支持直接使用TIFF、IMG等格式的图像，而不需要将它们转换为PNG、JPEG等视觉领域常见的图像格式，从而保留和利用图像中存储的地理空间信息。对于TIFF、IMG等格式的图像，包括`split.py`脚本的切分结果，可以使用ArcGIS、ENVI等遥感专业软件查看。此外，如果你确实需要将图像转换为PNG、JPEG等格式，可以考虑使用PaddleRS的[波段选择](https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/intro/transforms_cons_params_cn.md#selectband)和[标准化](https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/intro/transforms_cons_params_cn.md#normalize)数据变换算子处理`paddlers.transforms.decode_image`解码的图像，然后使用OpenCV、scikit-image等库将图像保存为预期的格式。
