### ISSUE TITLE
[General Issue]如何有效的处理遥感大图和对应的Shp文件，将其转为对应的coco格式？

### ISSUE THREAD

**Issue by tms2003** [PaddlePaddle/PaddleRS#199]
我有一张大图（tiff或img格式）和对应的shp文件，shp文件是对大图的标注(mask)。如何才能有效的使用paddlers的工具，来实现把大图切为小图，生成对应的coco格式的mask，方便进行训练呢？

示例中都是已经处理好图像，我希望能有效的使用paddlers中的工具来实现这个需求， 谢谢！

**Comment by Bobholamovic** [comment]
你好，很遗憾，由于PaddleRS的分割任务并不支持COCO格式的标注，因此PaddleRS没有提供生成COCO格式的mask的工具～

对于大图切成小图，可以参考`split.py`工具：https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/data/tools_cn.md#split
