### ISSUE TITLE
[General Issue]关于https://github.com/PaddlePaddle/PaddleRS/blob/develop/examples/c2fnet/README.md中的label生成问题

### ISSUE THREAD

**Issue by tms2003** [PaddlePaddle/PaddleRS#201]
原文：
```
其中train.txt、val.txt、label.txt可以参考[PaddleSeg](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/data/marker/marker_cn.md)的方式生成。
```

然而，PaddleSeg并不包括生成label.txt。paddleSeg中的train.txt和val.txt中已经包括了label图。而train.py中又使用了label.txt，它应当是什么格式呢？

**Comment by Bobholamovic** [comment]
你好，`label.txt`是一个文本文件，其中每一行包含一个类别的名称。对于isaid数据集，可以使用PaddleRS提供的脚本生成符合PaddleRS格式要求的数据：https://github.com/PaddlePaddle/PaddleRS/blob/develop/tools/prepare_dataset/prepare_isaid.py
