### ISSUE TITLE
预训练问题

### ISSUE THREAD

**Issue by nwnuszu** [PaddlePaddle/PaddleRS#205]
我在torchgeo网站的介绍中看到，你们有14个模型的预训练权重。但我在你们的github中并未找到相关说明。请问是否有预训练模型，如果有在哪里可以找到？

**Comment by Bobholamovic** [comment]
你好，这部分暂时没有文档。你可以在[这个文件](https://github.com/PaddlePaddle/PaddleRS/blob/develop/paddlers/utils/checkpoint.py)中找到所有的预训练权重的链接。
