### ISSUE TITLE
[Bug]部署模型文件缺少model.pdiparams

### ISSUE THREAD

**Issue by 1528242627** [PaddlePaddle/PaddleRS#207]
欢迎您反馈PaddleRS使用问题。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：develop
 2. PaddlePaddle版本：PaddlePaddle 2.6.1
 3. 操作系统信息：Windows
 4. Python版本号：Python3.8
 5. CUDA/cuDNN版本：CUDA11.2/cuDNN 8.x
 6. 完整的代码：
 import subprocess
# 设置要运行的命令
command = [
    'python', 'C:/Users/KKR/Desktop/PaddleRS-develop/deploy/export/export_model.py',
    '--model_dir=./output/fast_scnn/best_model/', 
    '--save_dir=./inference_model/',
    '--fixed_input_shape=[-1,10,224,224]'
]
# 运行命令
subprocess.run(command)

 8. 详细的错误信息与相关log：（若使用多卡，log默认保存在`log/worklog.0`）
 9. 问题复现步骤：使用测试demo里的Fast-SCNN模型部署时，deploy/export/README.md中提供的部署模型导出命令，生成的模型文件只有.success，model.pdiparams.info，model.pdmodel，model.yml，pipeline.yml五个文件，缺少model.pdiparams文件

 11. 其他内容:

**Comment by 1528242627** [comment]
目前排查的问题原因可能是模型参数没有正确加载，load_model函数只给了warning。。2024-07-22 15:36:06 [WARNING]   Cannot find raw_params. Default arguments will be used to construct the model.

**Comment by 1528242627** [comment]
已解决，原因是相对路径中含有中文

**Comment by Bobholamovic** [comment]
考虑到问题已经解决，我将关闭这个issue。有其他问题欢迎重启这个issue或者发起新的issue～
