### ISSUE TITLE
PaddleRS 微信群 过期了,PaddleRS 是否合适 大分辨率的PCB主板检测

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleRS#3]
PaddleRS 微信群 过期了

另外 PaddleRS 是否合适 大分辨率的PCB主板检测

**Comment by Bobholamovic** [comment]
您好，感谢提醒，我们将尽快更新二维码！

目前PaddleRS主要对带有地理坐标信息的遥感大图做了优化（延迟载入内存、滑窗推理等），可能并不适合处理大分辨率的PCB主板检测。针对您的问题，可以尝试在[PaddleSeg](https://github.com/PaddlePaddle/PaddleSeg)找到相应的解决方案。

**Comment by jianlong-yuan** [comment]
有新的微信群吗？

**Comment by Bobholamovic** [comment]
微信群已更新哈～
