### ISSUE TITLE
mask2geojson.py 不可用

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/PaddleRS#53]
parser = argparse.ArgumentParser()
    parser.add_argument("--mask_path", type=str, required=True, \
                        help="Path of mask data.")
    parser.add_argument("--save_path", type=str, required=True, \
                        help="Path to store the GeoJSON file (the coordinate system is WGS84).")
    args = parser.parse_args()
    convert_data(args.raster_path, args.geojson_path)

参数是mask_path save_path 而convert_data(args.raster_path, args.geojson_path) 参数根本不一样，这个脚本是否可用，是否做过测试，谢谢

**Comment by Bobholamovic** [comment]
感谢反馈，这是一个bug，之前的测试没有发现，现在已经修复~ PaddleRS提供的实际功能应该是`geojson2mask`。

**Comment by zgsxwsdxg** [comment]
> 感谢反馈，这是一个bug，之前的测试没有发现，现在已经修复~ PaddleRS提供的实际功能应该是`geojson2mask`。

你们readme中提到，可以将预测mask图片png 转成 geojson 是哪个工具？谢谢

**Comment by zgsxwsdxg** [comment]
> 感谢反馈，这是一个bug，之前的测试没有发现，现在已经修复~ PaddleRS提供的实际功能应该是`geojson2mask`。
[mask2geojson.py](https://github.com/PaddlePaddle/PaddleRS/blob/develop/tools/mask2geojson.py) 这个是实现 预测mask 图片转geojson吗？但是好像也不能用

**Comment by Bobholamovic** [comment]
> > 感谢反馈，这是一个bug，之前的测试没有发现，现在已经修复~ PaddleRS提供的实际功能应该是`geojson2mask`。
> 
> 你们readme中提到，可以将预测mask图片png 转成 geojson 是哪个工具？谢谢

你好，这个功能现在已经删除了，可能文档没有及时更新。请问你是在哪个README里找到的呀？

**Comment by zgsxwsdxg** [comment]
> > > 感谢反馈，这是一个bug，之前的测试没有发现，现在已经修复~ PaddleRS提供的实际功能应该是`geojson2mask`。
> > 
> > 
> > 你们readme中提到，可以将预测mask图片png 转成 geojson 是哪个工具？谢谢
> 
> 你好，这个功能现在已经删除了，可能文档没有及时更新。请问你是在哪个README里找到的呀？

https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/data/tools.md

**Comment by zgsxwsdxg** [comment]
> > > 感谢反馈，这是一个bug，之前的测试没有发现，现在已经修复~ PaddleRS提供的实际功能应该是`geojson2mask`。
> > 
> > 
> > 你们readme中提到，可以将预测mask图片png 转成 geojson 是哪个工具？谢谢
> 
> 你好，这个功能现在已经删除了，可能文档没有及时更新。请问你是在哪个README里找到的呀？
https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/data/tools.md


> > > 感谢反馈，这是一个bug，之前的测试没有发现，现在已经修复~ PaddleRS提供的实际功能应该是`geojson2mask`。
> > 
> > 
> > 你们readme中提到，可以将预测mask图片png 转成 geojson 是哪个工具？谢谢
> 
> 你好，这个功能现在已经删除了，可能文档没有及时更新。请问你是在哪个README里找到的呀？

我发现你们好像 readme修改了，但是新的https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/data/tools.md readme中提到 mask2shape.py：用于将模型推理输出的.png格式栅格标签转换为.shp矢量格式。这个mask2shape.py可用是吧？能实现预测的图片mask转为.shp文件的功能？谢谢！！！

**Comment by Bobholamovic** [comment]
`mask2shape.py`脚本是可以使用的，欢迎尝试，如果遇到问题或者找到bug也请在issue里提出~
