### ISSUE TITLE
[General Issue]介绍里有影像配准功能，具体有文档吗？或者图像配准功能的文档

### ISSUE THREAD

**Issue by RainFrost1** [PaddlePaddle/PaddleRS#62]
Thanks for your issue. To help us better solve the issue, please provide the following information：
 1. PaddleRS version: (please specify the branch as well，e.g. PaddleRS release/1.0)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.3.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (add any other context about the problem)

---

欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：（请提供版本号和分支信息，如PaddleRS release/1.0）
 2. PaddlePaddle版本：（如PaddlePaddle 2.3.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by Bobholamovic** [comment]
你好，请参考：https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/data/tools.md#match
