### ISSUE TITLE
[Question] PyTorch Version of FactSeg

### ISSUE THREAD

**Issue by twsha** [PaddlePaddle/PaddleRS#66]
Welcome to request a new feature! To help us better understand your request, please provide the following information:
1. A clear and concise description of the requested feature.
2. Tell us why the feature will be useful.
3. If possible, please show related codes.

---

欢迎提出一个新的功能需求。为了帮助我们更好理解您的需求，辛苦您提供以下信息：

1. 请使用清晰简洁的语言描述该项功能需求。
2. 请分析这个功能的必要性。
3. 如果可能的话，请提供相关代码实现效果。

你好博主，请问可以有没有复现factseg的torch版训练过程，真的很需要torch版，谢谢博主，感谢博主

**Comment by Bobholamovic** [comment]
你好，请参考 [FactSeg官方仓库](https://github.com/Junjue-Wang/FactSeg) 。

**Comment by twsha** [comment]
> 你好，请参考 [FactSeg官方仓库](https://github.com/Junjue-Wang/FactSeg) 。

原码的训练过程可读性较差，单卡无法跑通，请问torch版能不能复现。

**Comment by Bobholamovic** [comment]
> > 你好，请参考 [FactSeg官方仓库](https://github.com/Junjue-Wang/FactSeg) 。
> 
> 原码的训练过程可读性较差，单卡无法跑通，请问torch版能不能复现。

本仓库是基于PaddlePaddle框架实现的，所以没有提供相应的PyTorch版本~ 如果对框架没有那么严格的要求的话，建议可以尝试一下Paddle版本的FactSeg，数据集准备脚本、训练教程和模型实现分别如下：

- [iSAID数据集准备脚本](https://github.com/PaddlePaddle/PaddleRS/blob/release/1.0/tools/prepare_dataset/prepare_isaid.py)：下载好iSAID数据集后执行此脚本进行预处理；
- [训练教程](https://github.com/PaddlePaddle/PaddleRS/blob/release/1.0/tutorials/train/semantic_segmentation/factseg.py)：单卡、多卡均支持；
- [模型实现代码](https://github.com/PaddlePaddle/PaddleRS/blob/release/1.0/paddlers/rs_models/seg/factseg.py)：其中复用了一部分FarSeg的实现，在阅读时可能需要参考[FarSeg代码](https://github.com/PaddlePaddle/PaddleRS/blob/release/1.0/paddlers/rs_models/seg/farseg.py)。

PaddlePaddle 2.0在使用上和PyTorch很接近，如果你熟悉PyTorch的话，应该很快就能上手。

如果对框架要求严格、限定只允许使用PyTorch的话，建议还是基于原作者提供的代码进行开发，或者可以考虑对PaddleRS现有的代码进行迁移（不过这可能会带来比较大的工程量）。

**Comment by twsha** [comment]
> > > 你好，请参考 [FactSeg官方仓库](https://github.com/Junjue-Wang/FactSeg) 。
> > 
> > 
> > 原码的训练过程可读性较差，单卡无法跑通，请问torch版能不能复现。
> 
> 本仓库是基于PaddlePaddle框架实现的，所以没有提供相应的PyTorch版本~ 如果对框架没有那么严格的要求的话，建议可以尝试一下Paddle版本的FactSeg，数据集准备脚本、训练教程和模型实现分别如下：
> 
> * [iSAID数据集准备脚本](https://github.com/PaddlePaddle/PaddleRS/blob/release/1.0/tools/prepare_dataset/prepare_isaid.py)：下载好iSAID数据集后执行此脚本进行预处理；
> * [训练教程](https://github.com/PaddlePaddle/PaddleRS/blob/release/1.0/tutorials/train/semantic_segmentation/factseg.py)：单卡、多卡均支持；
> * [模型实现代码](https://github.com/PaddlePaddle/PaddleRS/blob/release/1.0/paddlers/rs_models/seg/factseg.py)：其中复用了一部分FarSeg的实现，在阅读时可能需要参考[FarSeg代码](https://github.com/PaddlePaddle/PaddleRS/blob/release/1.0/paddlers/rs_models/seg/farseg.py)。
> 
> PaddlePaddle 2.0在使用上和PyTorch很接近，如果你熟悉PyTorch的话，应该很快就能上手。
> 
> 如果对框架要求严格、限定只允许使用PyTorch的话，建议还是基于原作者提供的代码进行开发，或者可以考虑对PaddleRS现有的代码进行迁移（不过这可能会带来比较大的工程量）。

x谢谢
