### ISSUE TITLE
[Bug]AttributeError: module 'paddlers.transforms' has no attribute 'DecodeImg'

### ISSUE THREAD

**Issue by iEdric** [PaddlePaddle/PaddleRS#70]
(pytorch37pp) cl@cl:~/pp/PaddleRS/tutorials/train/semantic_segmentation$ python deeplabv3p.py 
/home/cl/anaconda3/envs/pytorch37pp/lib/python3.7/site-packages/paddlers/models/ppcls/data/preprocess/ops/timm_autoaugment.py:38: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  _RANDOM_INTERPOLATION = (Image.BILINEAR, Image.BICUBIC)
/home/cl/anaconda3/envs/pytorch37pp/lib/python3.7/site-packages/paddlers/models/ppcls/data/preprocess/ops/timm_autoaugment.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  _RANDOM_INTERPOLATION = (Image.BILINEAR, Image.BICUBIC)
2022-11-23 17:59:51 [INFO]      Decompressing ./data/rsseg.zip...
2022-11-23 18:00:00 [DEBUG]     ./data/rsseg.zip decompressed.
Traceback (most recent call last):
  File "deeplabv3p.py", line 32, in <module>
    T.DecodeImg(),
AttributeError: module 'paddlers.transforms' has no attribute 'DecodeImg'

**Comment by Bobholamovic** [comment]
请检查环境中是否存在不同版本的PaddleRS，例如之前安装过旧版本的PaddleRS。

**Comment by iEdric** [comment]
没有安装过，新的conda环境

**Comment by iEdric** [comment]
> 请检查环境中是否存在不同版本的PaddleRS，例如之前安装过旧版本的PaddleRS。


没有安装过，新的conda环境

**Comment by Bobholamovic** [comment]
请在以上出现错误中的环境执行如下指令：
```shell
python -c "import paddlers; print(paddlers)"
```

找到打印出的PaddleRS安装路径中`paddlers/transforms/operators.py`目录，确认其中是否存在`DecodeImg`方法。
