### ISSUE TITLE
Can you share your WeChat QR code again? The posted was expired. 

### ISSUE THREAD

**Issue by metacav** [PaddlePaddle/PaddleRS#75]
Can you share your WeChat QR code again? The posted was expired.

**Comment by Bobholamovic** [comment]
Thanks for letting us know. We have updated the WeChat QR code. Please check [here](https://github.com/PaddlePaddle/PaddleRS#-%E6%8A%80%E6%9C%AF%E4%BA%A4%E6%B5%81).
