### ISSUE TITLE
I am wondering whether you share the pertained checkpoint for each model?

### ISSUE THREAD

**Issue by metacav** [PaddlePaddle/PaddleRS#77]

**Comment by Bobholamovic** [comment]
Currently we provide pretrained checkpoints for some of the models. You can specify the pretrained weights to use with the `pretrain_weights` argument in the training API. An example of using model weights pretrained on the iSAID dataset can be found [here](https://github.com/PaddlePaddle/PaddleRS/blob/f9898b7a183e78613a127283246f019545783458/tutorials/train/semantic_segmentation/factseg.py#L87).
