### ISSUE TITLE
[Bug]AttributeError: module 'paddlers.tasks' has no attribute 'changedetector'

### ISSUE THREAD

**Issue by LinBaihao** [PaddlePaddle/PaddleRS#78]
Hi there! Thanks for your tremendous efforts in this repo, and I hope you guys are doing well. Anyway, I've encountered some problems with the change detection. When I tried to export a static model or try slide_detector of change detection, they both had the AttributeError: module 'paddlers.tasks' has no attribute 'changedetector'. So that's the reason why I am here, and wondering if you could offer me some help with this issue.

Here are some environment details listed below in case you might need them.

All tasks were running on Ubuntu 18.04 LTS.
Traceback (most recent call last):
  File "deploy/export/export_model.py", line 73, in <module>
    model = load_model(args.model_dir)
  File "/home/supermicro3090/anaconda3/envs/rs/lib/python3.7/site-packages/paddlers-develop-py3.7.egg/paddlers/tasks/load_model.py", line 77, in load_model
    mod = getattr(paddlers.tasks, model_type)
AttributeError: module 'paddlers.tasks' has no attribute 'changedetector'

conda list | grep paddle
paddle-bfloat             0.1.7                    pypi_0    pypi
paddlepaddle-gpu          2.3.2.post112            pypi_0    pypi
paddlers                  develop                  pypi_0    pypi
paddleslim                2.3.4                    pypi_0    pypi

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0

Please let me know if you need anything else.

**Comment by Bobholamovic** [comment]
Hi, can you provide the specific version of PaddleRS you are using (e.g. the commit id)?

**Comment by LinBaihao** [comment]
Here's what I got by using command git log, I'm not sure if this is what you need.
git log
commit 35e95b77cf42053c5eff748cc6d5ee0b33d4434a (HEAD -> develop, origin/develop, origin/HEAD)
Author: Bobholamovic <mhlin425@whu.edu.cn>
Date:   Tue Dec 13 10:19:17 2022 +0800

    Update QR Code

commit f9898b7a183e78613a127283246f019545783458
Author: Lin Manhui <mhlin425@whu.edu.cn>
Date:   Tue Dec 13 10:09:43 2022 +0800

    Update README.md

commit 4c58e9c936e2e72d81b75a499641268ce42720e1
Author: Lin Manhui <mhlin425@whu.edu.cn>
Date:   Mon Dec 12 18:05:49 2022 +0800

    Update README.md

commit 129520aaae2c785285163c6c4cd1125676466f71
Author: Lin Manhui <mhlin425@whu.edu.cn>
Date:   Mon Dec 12 16:32:11 2022 +0800

**Comment by Bobholamovic** [comment]
Yes, this means you are currently using state-of-the-art code. Please check the `model.yml` file in the model directory you were trying to export from (i.e. the path specified by `--model_dir`) and make sure the `model_type` item in this file has the value `change_detector`. If the value is `changedetector`, the model was probably trained with a much older and incompatible version of PaddleRS, and you may have to downgrade the library or re-train the model with the newest version of PaddleRS.

**Comment by LinBaihao** [comment]
Sounds pretty reasonable. If everything works fine after that, I would close this issue asap. Appreciate it.

**Comment by LinBaihao** [comment]
I'm sorry for not getting back to you sooner, but Covid 19 just got the better of me. After training a new model, everything works perfectly fine.
