### ISSUE TITLE
[Bug]paddle::pybind::ThrowExceptionToPython(std::-_exception_ptr::exception_ptr)

### ISSUE THREAD

**Issue by yiiizuo** [PaddlePaddle/PaddleRS#80]
欢迎您反馈PaddleRS使用问题。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：（请提供版本号和分支信息，如PaddleRS release/1.0）
develop branch
 2. PaddlePaddle版本：（如PaddlePaddle 2.3.0）
paddle2.4.1.post17
 3. 操作系统信息：（如Linux/Windows/MacOS）
ubuntu20.04
 5. Python版本号：（如Python3.7/8）
python3.9
 7. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
cuda11.7，cudnn8.4.0，nccl2.14.3
 9. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
我在changdetection中能够运行bit、cdnet、fc_sian_diff，但是当我运行sunet、stanet、changeformer时，终端给我报错了。相关运行代码为
python run_task.py train cd --config "test_tipc/configs/cd/stanet/stanet_levircd.yaml"
 11. 详细的错误信息与相关log：（若使用多卡，log默认保存在`log/worklog.0`）

[2022-12-16 20:50:31,484] [[2022-12-16 20:50:31,485] [[2022-12-16 20:50:31,674] [
INFO] download.py:119 - unique_endpoints {'}INFO] download.py:273  File /home/zy/.cache/paddle/hapi/weights/resnet18.pdparams md5 checking...INFO] download.py:156 - Found /home/zy/.cache/paddle/hapi/weights/resnet18.pdparams
C++ Traceback (most recent call last):paddle::pybind::ThrowExceptionToPython(std::-_exception_ptr::exception_ptr)
--------------------
Error Message Summary:----------------------
FatalError: Process abort signal' is detected by the operating system.[TimeInfo: *** Aborted at 1671195045 (unix time) try "date -d @1671195045" if you are using GNU date ***][SignalInfo: *** SIGABRT (@0x3e8000a67d7) received by PD 681943 (TID 0x7f60273e3180) from PID 681943 ***]
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

 13. 问题复现步骤：
相同环境下，运行sunet、stanet、changeformer等变换检测代码即可复现。

 15. 其他内容: （增加其他与问题相关的内容）

**Comment by Bobholamovic** [comment]
这应该是由于显存不足导致的。STANet 的一个显著特点是使用了时空注意力模块，该模块密集连接两个时相特征图，计算任意两个像素之间的相关关系，因此十分消耗显存。在使用 STANet 时，需要尤其注意输入图像的尺寸不宜过大。

**Comment by yiiizuo** [comment]
> stanet的。不足不足的的个特点使用了时空时空注意力注意力使用STANet时，需要尤其注意输入图像的尺寸宜过大。

感谢您的回复，待我明天实验成功后，就会关闭这个问题
