### ISSUE TITLE
pip install -r requirements.txt执行失败

### ISSUE THREAD

**Issue by gisfzb** [PaddlePaddle/PaddleRS#82]
![image](https://user-images.githubusercontent.com/45624812/209051092-57773065-db03-4d6b-be35-5e3ee5faa9e3.png)
执行pip install -r requirements.txt命令报这个错，是缺少什么环境依赖吗，macOS系统，M1的处理器，python版本是3.8.16

**Comment by Bobholamovic** [comment]
看起来是 NumPy 编译失败了，可以考虑下载版本匹配的已编译好的包

**Comment by gisfzb** [comment]
PaddleRS源码编译依赖其他啥环境吗

**Comment by Bobholamovic** [comment]
paddlers release/1.0 源码不需要编译，这个错误是安装依赖库的时候出现的哈

**Comment by gisfzb** [comment]
安装依赖库需要哪些基础环境支持呢？

**Comment by Bobholamovic** [comment]
> 安装依赖库需要哪些基础环境支持呢？

需要安装 PaddlePaddle 框架、（可选）GDAL 以及 `requirements.txt` 中列出的依赖库。一般按照官方教程执行安装即可，如果出现某几个依赖安装不上的情况，可能需要手动安装。比如这个错误提示可能需要手动安装 NumPy。

**Comment by gisfzb** [comment]
scikit-learn依赖安装失败，这个依赖是有啥环境要求吗

**Comment by Bobholamovic** [comment]
> scikit-learn依赖安装失败，这个依赖是有啥环境要求吗

应该和所需要安装的版本以及你本地的环境有关，具体可参考 [scikit-learn 官网](https://scikit-learn.org/stable/)。
