### ISSUE TITLE
[General Issue]我想问下paddlers中的图像分割模型和paddlex中样例工程的遥感影像分割有什么不同。

### ISSUE THREAD

**Issue by bingoodog** [PaddlePaddle/PaddleRS#95]
Thanks for your issue. To help us better solve the issue, please provide the following information：
 1. PaddleRS version: (please specify the branch as well，e.g. PaddleRS release/1.0)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.3.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (add any other context about the problem)

---

欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：（请提供版本号和分支信息，如PaddleRS release/1.0）
 2. PaddlePaddle版本：（如PaddlePaddle 2.3.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by Bobholamovic** [comment]
你好，PaddleX 和 PaddleRS 的侧重点不同：

- PaddleX 是智能**视觉**领域的全流程开发工具，支持分割、检测、分类等通用视觉任务。PaddleX 的主要优势在于低代码全流程开发与强大的多端部署能力。
- PaddleRS 是针对**遥感**领域打造的全流程开发工具，专注于遥感任务。PaddleRS 支持 PaddleX 不具备的多波段影像预处理、遥感指数提取、大幅影像推理、道路补全、建筑物边界规范化等功能，同时支持遥感专用模型（如针对遥感影像性质设计的分割模型 FarSeg 和 FactSeg）。

由于在特定情况下（例如针对只有三个波段且事先经过辐射校正、裁块等预处理的遥感影像）使用通用视觉模型处理遥感影像是可行的，因此 PaddleX 也支持一部分遥感任务。
