### ISSUE TITLE
如何实现多机训练？

### ISSUE THREAD

**Issue by KrisZHH** [PaddlePaddle/PaddleRS#98]
这套代码是否支持多机训练呢？如果支持的话，要如何启动？如果不支持，未来会计划支持吗？

**Comment by Bobholamovic** [comment]
你好，目前PaddleRS支持多机训练，请参考 PaddlePaddle 多机训练指南：

https://www.paddlepaddle.org.cn/tutorials/projectdetail/479613#anchor-6

使用指南中提示的方式调用 PaddleRS 训练脚本即可。使用过程中如果遇到困难或者发现 bug，欢迎向我们反馈。
